# Generated by Django 3.2.6 on 2021-08-08 11:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('fatherName', models.CharField(max_length=70)),
                ('dob', models.CharField(max_length=10)),
                ('domicile', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=255)),
                ('courseCategory', models.CharField(max_length=3)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2021, 8, 8, 16, 34, 52, 745117))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
