# Generated by Django 3.2.6 on 2021-08-08 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 17, 29, 7, 113833)),
        ),
        migrations.AlterField(
            model_name='details',
            name='dob',
            field=models.DateField(max_length=10),
        ),
    ]
