# Generated by Django 3.2.6 on 2021-08-09 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20210808_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 12, 3, 1, 879661)),
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primaryPhoneNumber', models.CharField(max_length=20)),
                ('secondaryPhoneNumber', models.CharField(max_length=20)),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phoneNumbers', to='user_details.details')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mailingAddress', models.CharField(max_length=255)),
                ('residentialAddress', models.CharField(max_length=255)),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user_details.details')),
            ],
        ),
    ]
