# Generated by Django 3.2.6 on 2021-08-09 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_auto_20210809_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 13, 51, 5, 502780)),
        ),
    ]
