# Generated by Django 3.2.6 on 2021-08-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_alter_details_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
