# Generated by Django 3.2.6 on 2021-08-10 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_auto_20210810_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
