# Generated by Django 3.2.6 on 2021-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0006_auto_20210810_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='dob',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
