# Generated by Django 3.2.6 on 2021-09-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0008_alter_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phoneNumber', to='user_details.details'),
        ),
    ]
