# Generated by Django 3.2.6 on 2021-08-12 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0003_auto_20210811_1244'),
        ('batch', '0003_auto_20210812_0838'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=30)),
                ('courseCode', models.CharField(max_length=10)),
                ('isUniElective', models.BooleanField(default=False)),
                ('isStudentElective', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('academicTerm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='batch.academicterm')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterDetails', to='batch.batches')),
                ('departmentProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterDetails', to='department.departmentprogram')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isCompleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('semesterDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterEnrollment', to='semester.semesterdetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesterEnrollment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferedCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('semesterCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='semester.semestercourses')),
                ('semesterDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offeredCourses', to='semester.semesterdetail')),
            ],
        ),
    ]
