# Generated by Django 3.2.6 on 2021-08-12 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_auto_20210812_0838'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preference', '0002_auto_20210810_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('offeredProgram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='batch.offeredprograms')),
                ('preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='preference.preferences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CoursePreference',
        ),
    ]
