# Generated by Django 3.2.6 on 2021-09-07 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isProfile', models.BooleanField(default=False)),
                ('isCourseCategory', models.BooleanField(default=False)),
                ('isFirstYear', models.BooleanField(default=False)),
                ('isSecondYear', models.BooleanField(default=False)),
                ('isThirdYear', models.BooleanField(default=False)),
                ('isFinalYear', models.BooleanField(default=False)),
                ('isGAT', models.BooleanField(default=False)),
                ('isMS', models.BooleanField(default=False)),
                ('isExperience', models.BooleanField(default=False)),
                ('isPreference', models.BooleanField(default=False)),
                ('isCnicFront', models.BooleanField(default=False)),
                ('isCnicBack', models.BooleanField(default=False)),
                ('isMatricCertificate', models.BooleanField(default=False)),
                ('isIntermediateCertificate', models.BooleanField(default=False)),
                ('isFirstSemesterDmc', models.BooleanField(default=False)),
                ('isSecondSemesterDmc', models.BooleanField(default=False)),
                ('isThirdSemesterDmc', models.BooleanField(default=False)),
                ('isFourthSemesterDmc', models.BooleanField(default=False)),
                ('isFifthSemesterDmc', models.BooleanField(default=False)),
                ('isSixthSemesterDmc', models.BooleanField(default=False)),
                ('isSeventhSemesterDmc', models.BooleanField(default=False)),
                ('isEighthSemesterDmc', models.BooleanField(default=False)),
                ('isBsCertificate', models.BooleanField(default=False)),
                ('isSubmitted', models.BooleanField(default=False)),
                ('isAccepted', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('acceptedBy', models.CharField(max_length=50, null=True)),
                ('rejectedBy', models.BooleanField(max_length=50, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('appId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicationStatus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
