# Generated by Django 3.2.6 on 2021-09-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_status', '0002_auto_20210907_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='rejectedBy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
