# Generated by Django 3.2.6 on 2021-08-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20210811_1244'),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedPrograms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offeredPrograms', to='batch.batches')),
                ('departmentProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='department.departmentprogram')),
            ],
        ),
        migrations.AddField(
            model_name='batches',
            name='programs',
            field=models.ManyToManyField(through='batch.OfferedPrograms', to='department.DepartmentProgram'),
        ),
    ]
