# Generated by Django 3.2.6 on 2021-08-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_auto_20210811_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Term',
            new_name='AcademicTerm',
        ),
        migrations.RenameField(
            model_name='batches',
            old_name='term',
            new_name='academicTerm',
        ),
    ]
