# Generated by Django 3.2.6 on 2021-08-18 10:42

from django.db import migrations


def code(apps, schema_editor):
    AcademicTerm = apps.get_model('batch', 'AcademicTerm')
    db_alias = schema_editor.connection.alias
    AcademicTerm.objects.using(db_alias).bulk_create([
        AcademicTerm(termName='fall'),
        AcademicTerm(termName='winter'),
        AcademicTerm(termName='spring'),
        AcademicTerm(termName='summer'),
    ])


def reverse_code(apps, schema_editor):
    AcademicTerm = apps.get_model('batch', 'AcademicTerm')
    db_alias = schema_editor.connection.alias
    AcademicTerm.objects.using(db_alias).filter(termName='fall').delete()
    AcademicTerm.objects.using(db_alias).filter(termName='winter').delete()
    AcademicTerm.objects.using(db_alias).filter(termName='spring').delete()
    AcademicTerm.objects.using(db_alias).filter(termName='summer').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_auto_20210812_0838'),
    ]

    operations = [
        migrations.RunPython(code, reverse_code)
    ]
