# Generated by Django 3.2.6 on 2021-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
