# Generated by Django 3.2.6 on 2021-08-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20210810_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='userAcademicRecords',
        ),
        migrations.AddField(
            model_name='academics',
            name='examYear',
            field=models.ManyToManyField(related_name='_academics_academics_examYear_+', through='academics.UserAcademicRecord', to='academics.ExamYear'),
        ),
        migrations.AlterField(
            model_name='useracademicrecord',
            name='academics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.academics'),
        ),
        migrations.AlterField(
            model_name='useracademicrecord',
            name='examYear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.examyear'),
        ),
    ]
