# Generated by Django 3.2.6 on 2021-08-12 13:37

from django.db import migrations


def code(apps, schema_editor):

    ExamYear = apps.get_model("academics", "ExamYear")
    db_alias = schema_editor.connection.alias
    ExamYear.objects.using(db_alias).bulk_create([
        ExamYear(examination="First Year"),
        ExamYear(examination="Second Year"),
        ExamYear(examination="Third Year"),
        ExamYear(examination="Final Year"),
        ExamYear(examination="GAT"),
        ExamYear(examination="MS"),
    ])


def reverse_code(apps, schema_editor):

    ExamYear = apps.get_model("academics", "ExamYear")
    db_alias = schema_editor.connection.alias
    ExamYear.objects.using(db_alias).filter(examination="First Year").delete()
    ExamYear.objects.using(db_alias).filter(examination="Second Year").delete()
    ExamYear.objects.using(db_alias).filter(examination="Third Year").delete()
    ExamYear.objects.using(db_alias).filter(examination="Final Year").delete()
    ExamYear.objects.using(db_alias).filter(examination="GAT").delete()
    ExamYear.objects.using(db_alias).filter(examination="MS").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20210810_2234'),
    ]

    operations = [
        migrations.RunPython(code, reverse_code)
    ]
