# Generated by Django 3.2.6 on 2021-08-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20210812_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useracademicrecord',
            old_name='examYear',
            new_name='examination',
        ),
        migrations.RemoveField(
            model_name='academics',
            name='examYear',
        ),
        migrations.AddField(
            model_name='academics',
            name='examination',
            field=models.ManyToManyField(related_name='academics', through='academics.UserAcademicRecord', to='academics.ExamYear'),
        ),
    ]
