# Generated by Django 3.2.6 on 2021-08-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_auto_20210813_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracademicrecord',
            name='examYear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicRecord', to='academics.examyear'),
        ),
    ]
