# Generated by Django 3.2.6 on 2021-09-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_useracademicrecord_academics'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='institue',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='academics',
            name='awards',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
