# Generated by Django 3.2.6 on 2021-08-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseCategory', models.CharField(max_length=3)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='department.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='department.departments')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ManyToManyField(related_name='courses', through='department.DepartmentCourse', to='department.Departments'),
        ),
    ]
