# Generated by Django 3.2.6 on 2021-08-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210810_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseCategory', models.CharField(max_length=3)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='department.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('department', models.ManyToManyField(related_name='programs', through='department.DepartmentProgram', to='department.Departments')),
            ],
        ),
        migrations.RemoveField(
            model_name='departmentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='departmentcourse',
            name='department',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='DepartmentCourse',
        ),
        migrations.AddField(
            model_name='departmentprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='department.programs'),
        ),
    ]
